### PR TITLE
feat: added the ability to activate the app with timeout

### PR DESCRIPTION
**Pull request by agentran**
## Change list
Adding timeout to the activate app function
 
## Types of changes

What types of changes are you proposing/introducing to .NET client?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] New feature (non-breaking change which adds value to the project)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Documentation
- [ ] Have you proposed a file change/ PR with appium to update documentation? 
## Integration tests
- [x] Have you provided integration tests to pass against the beta version of appium? (for Bugfix or New feature)

## Details

sometimes on slower emulators, activating the app requires more time then provided by default, this change solves it.

Please provide more details about changes if it is necessary. If there are new features you can provide code samples which show the way they
work and possible use cases. Also you can create [gists](https://gist.github.com) with pasted C# code samples or put them here using markdown. 
About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and [Writing on GitHub](https://help.github.com/categories/writing-on-github/)

### CODE REVIEW

**Comment by Dor-bl** [comment]
@agentran Thank you for the PR!
A couple of notes:
- Please sign the CLA. It is usually a one time thing, and is required for the PR to be merged.
- Rename the PR title to follow the [conventional commit format](https://conventionalcommits.org/)

**Comment by Dor-bl** [comment]
@agentran, I see you still haven't signed the CLA. Please do, if you would like to complete this PR.

**Comment by agentran** [comment]
> @agentran, I see you still haven't signed the CLA. Please do, if you would like to complete this PR.

Singed 👍

**Comment by Dor-bl** [comment]
@agentran thanks, just a little note.
Your PR is for the master branch which is the stable version. we are currently no longer maintaining that version, but rather focus on the beta releases. So you might want to add it there as well.
Thanks

**Review by akinsolb — APPROVED** [review]

**Comment by akinsolb** [comment]
@Dor-bl Just clocked your last comment. Will raise a ticket to add to v5

**Pull request merged**
