### PR TITLE
docs: Update NuGet badges  (Release 5.x)

### PR DESCRIPTION
**Pull request by Dor-bl**
## Change list

Add Build and Deploy NuGet badge + Change Nuget to use pre-release which is the only one relevant for 5.x branch

## Types of changes

What types of changes are you proposing/introducing to .NET client?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] New feature (non-breaking change which adds value to the project)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Documentation
- [x] Have you proposed a file change/ PR with appium to update documentation? 
## Integration tests
- [ ] Have you provided integration tests to pass against the beta version of appium? (for Bugfix or New feature)

## Details

Please provide more details about changes if it is necessary. If there are new features you can provide code samples which show the way they
work and possible use cases. Also you can create [gists](https://gist.github.com) with pasted C# code samples or put them here using markdown. 
About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and [Writing on GitHub](https://help.github.com/categories/writing-on-github/)

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]

**Review by laolubenson — APPROVED** [review]

**Comment by Dor-bl** [comment]
@KazuCocoa, Last time I discussed this option with @laolubenson he said we first need to add more docs for that release, I Still haven't got the time.
also, I'm not sure the best approach to replace the master with the 5.x. (I'm still finding my way through GitHub)
Should we delete the master branch and rename release/5.0.0 to main? 
Maybe we should first release an RC version?

**Comment by laolubenson** [comment]
> @KazuCocoa, Last time I discussed this option with @laolubenson he said we first need to add more docs for that release, I Still haven't got the time.
> 
> also, I'm not sure the best approach to replace the master with the 5.x. (I'm still finding my way through GitHub)
> 
> Should we delete the master branch and rename release/5.0.0 to main? 
> 
> Maybe we should first release an RC version? 

Yeah, perhaps we should put a date on it, cut and release for example on September 1st.

**Comment by KazuCocoa** [comment]
Sounds good to me.
For the branching, we could stay the current `master` as a new name such as `v4` branch for example, and make the 5.0 as main like https://github.com/appium/appium 's master -> v1 and v2 -> master

**Comment by Dor-bl** [comment]
I created a milestone for [5.0.0-rc1](https://github.com/appium/dotnet-client/milestone/6)
unless you guys want to skip the rc step

**Pull request merged**
