### PR TITLE
refactor: Rename repository to dotnet-client

### PR DESCRIPTION
**Pull request by Dor-bl**
In case we would like to rename the repo to match the other clients in the appium project, this is a good place to start.
As discussed with @akinsolb on slack

## Change list

Please provide briefly described change list which are you going to propose. 
 
## Types of changes

What types of changes are you proposing/introducing to .NET client?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] New feature (non-breaking change which adds value to the project)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Documentation
- [x] Have you proposed a file change/ PR with appium to update documentation? 
## Integration tests
- [ ] Have you provided integration tests to pass against the beta version of appium? (for Bugfix or New feature)

## Details

Please provide more details about changes if it is necessary. If there are new features you can provide code samples which show the way they
work and possible use cases. Also you can create [gists](https://gist.github.com) with pasted C# code samples or put them here using markdown. 
About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and [Writing on GitHub](https://help.github.com/categories/writing-on-github/)

### CODE REVIEW

**Review by akinsolb — APPROVED** [review]

**Comment by Dor-bl** [comment]
@jlipps any issue from your side with the idea of changing the repo name?

**Comment by Dor-bl** [comment]
I'll update here the places I encounter any links. 
- [ ] https://appium.github.io/appium/docs/en/2.0/ecosystem/

**Comment by Dor-bl** [comment]
@akinsolb should we move forward with the Rename? I can open a PR on Appium for the links change

**Comment by Dor-bl** [comment]
@akinsolb should we rename the Product value in the .csproj as well? 
    <Product>Appium-Dotnet-Driver</Product>

**Comment by akinsolb** [comment]
> @akinsolb should we rename the Product value in the .csproj as well? 
> 
>     <Product>Appium-Dotnet-Driver</Product>

Yep

**Comment by Dor-bl** [comment]
> > @akinsolb should we rename the Product value in the .csproj as well?
> > ```
> > <Product>Appium-Dotnet-Driver</Product>
> > ```
> 
> Yep

Done

**Pull request merged**
