### PR TITLE
chore: update iOS-specific capabilities docs hyperlink

### PR DESCRIPTION
**Pull request by Dor-bl**
## List of changes

Updated the docs link to use the new docs page of ios caps
 
## Types of changes

What types of changes are you proposing/introducing to the .NET client?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] New feature (non-breaking change which adds value to the project)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

## Documentation
- [ ] Have you proposed a file change/ PR with appium to update documentation? 
## Integration tests
- [ ] Have you provided integration tests to pass against the beta version of appium? (for Bugfix or New feature)

## Details

Please provide more details about changes if it is necessary. If there are new features you can provide code samples showing how they work and possible use cases. Also, you can create [gists](https://gist.github.com) with pasted C# code samples or put them here using markdown. 
About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and [Writing on GitHub](https://docs.github.com/en/get-started/writing-on-github)

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]
Or can be GitHub a link since the typedoc will be changed potentially (it would be hard to keep maintaining)

**Comment by Dor-bl** [comment]
> Or can be GitHub a link since the typedoc will be changed potentially (it would be hard to keep maintaining)

Do you refer to this?
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/capabilities.md

**Comment by KazuCocoa** [comment]
Yes, either is good for now though

**Comment by Dor-bl** [comment]
> Yes, either is good for now though

done

**Review by KazuCocoa — APPROVED** [review]

**Pull request merged**
