### PR TITLE
chore: Deprecate legacy app management helpers

### PR DESCRIPTION
**Pull request by Dor-bl**
## Change list

As mentioned in https://github.com/appium/appium/issues/15807, these methods will not be supported anymore.
Related item:
https://github.com/appium/dotnet-client/issues/562
For now, I updated only one Integration test to use the more standard Appium session management, more will follow.
 
## Types of changes

What types of changes are you proposing/introducing to .NET client?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] New feature (non-breaking change which adds value to the project)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Documentation
- [ ] Have you proposed a file change/ PR with appium to update documentation? 
## Integration tests
- [x] Have you provided integration tests to pass against the beta version of appium? (for Bugfix or New feature)

## Details

Please provide more details about changes if it is necessary. If there are new features you can provide code samples which show the way they
work and possible use cases. Also you can create [gists](https://gist.github.com) with pasted C# code samples or put them here using markdown. 
About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and [Writing on GitHub](https://help.github.com/categories/writing-on-github/)

### CODE REVIEW

**Review by laolubenson — APPROVED** [review]

**Comment by Dor-bl** [comment]
Cheers @laolubenson.
@mykola-mokhnach  @KazuCocoa your input will be appreciated as well.

**Comment by laolubenson** [comment]
Ideally, we should advise users on how to use the mobile script method

**Comment by KazuCocoa** [comment]
Yea, a link to https://github.com/appium/appium/issues/15807 may help to see more details.
e.g. https://github.com/appium/python-client/blob/4031de2aad7918da0e3b083fc2be5a37865e4d79/appium/webdriver/extensions/applications.py#LL114C18-L114C63

or adding alternative methods as https://github.com/appium/ruby_lib_core/blob/e6bc18853305f5b81c3be8a201ac0f9528e772ea/lib/appium_lib_core/common/device/app_management.rb#L22 also may help. (maybe the github link should be sufficient)

**Comment by Dor-bl** [comment]
@KazuCocoa, @laolubenson I've improved the deprecation messages.
let me know if I missed anything else

**Review by KazuCocoa — APPROVED** [review]
lgtm, thanks!

**Review by laolubenson — APPROVED** [review]

**Pull request merged**
